name = "Prominence II RPG Hasturian Era"
author = "ElocinDev"
version = "v3.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aae405c9190f8c6ad012b407cea08d5fcd6065cb8f27c9f77561fa9e249cca71"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
